spring:
  application:
    name:
      stockpin
  data:
    redis:
      port: 6379
      host: localhost
      
api:
  appkey: PSVRKOsVWWoHs04ufNkd2Y4WYRKMnKdgkwnU
  appsecret: O/C2GGA7fN4v8B8dML8K5MtcRCyNzPBQ61lO0nIUzhP9A+L0M0YuJmzs5p8j4buR4yv4Th8wpE11f8VVGtkzSHYLfugFMh4zfU0opujKpP2dOsbSqTaLZTlN0vbMGMZsnD0oVpzat0S0b30asXqNMHV7GAEH7cSZ9xmnvge1cAaNe9ULRss=